linters:
  SpaceBeforeBrace:
    enabled: false

  Indentation:
    enabled: true
    width: 2

  StringQuotes:
    style: double_quotes

  LeadingZero:
    style: include_zero

  NameFormat:
    convention: BEM

  PropertySortOrder:
    order:
      - any
    ignore_unspecified: true
